# This is a basic workflow to help you get started with Actions

name: deployment to Github-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.1

      # Send a notification in slack
      # - name: Send a start pipeline notification to Slack
      #   run: echo Send a start pipeline notification to Slack in master branch

      # Runs npm install
      - name: yarn install
        run: yarn

      # Runs tests
      # - name: run tests
      #   run: npm run test

      # Generate build
      - name: generate build
        run: yarn build
        env:
          CONTRACT_NAME: ${{ secrets.CONTRACT_NAME }}
          REACT_APP_ETHERSCAN_URL: ${{ secrets.REACT_APP_ETHERSCAN_URL }}
          API_URL: ${{ secrets.API_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REACT_APP_CONTRACT_ADDRESS: ${{ secrets.REACT_APP_CONTRACT_ADDRESS }}
          REACT_APP_CONTRACT_REGISTRY_ADDRESS: ${{ secrets.REACT_APP_CONTRACT_REGISTRY_ADDRESS }}
          CONTRACT_REGISTRY: ${{ secrets.CONTRACT_REGISTRY }}

      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
